---
- name: Install Nginx web server
  ansible.builtin.apt:  
    name: nginx
    update_cache: yes
    state: latest
  tags:
    - dependencies
    - webapp

- name: Copy nginx configuration
  ansible.builtin.template: 
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  tags:
    - webapp