---
- name: Install php and dependencies
  ansible.builtin.apt:  
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
    - php7.4
    - php7.4-fpm
    - php7.4-mysql
  tags:
    - dependencies
    - webapp

- name: Copy php configuration
  ansible.builtin.template: 
    src: php.ini.j2
    dest: /etc/php/7.4/fpm/php.ini
  tags:
    - webapp
  notify: 
    - restart_php-fpm